M48
; DRILL file {KiCad 8.0.4} date 2024-11-09T11:53:40-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-09T11:53:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.9676Y-3.9567
X4.9676Y-5.689
X6.6999Y-3.9567
X6.6999Y-5.689
M30
